#!/usr/bin/env bash

DIR=$1
URL=$2
BRANCH=$3
CONFIG=$4

if [ "$#" -ne 4 ]; then
  echo "Usage: checkout-doxygen DIRECTORY URL BRANCH CONFIG"
  exit 1
fi

if [ ! -d $DIR ]; then
  git clone $URL $DIR
fi

(cd $DIR git && git checkout $BRANCH && git pull --rebase)

(cat $CONFIG ; echo -e "PROJECT_BRIEF=\"($BRANCH)\"\nPROJECT_NUMBER=\"$($HOME/v8-doxygen/scripts/version)\"") | doxygen -
