#!/usr/bin/env bash

grep -E '^#define\sV8_(MAJOR_VERSION|MINOR_VERSION|BUILD_NUMBER|PATCH_LEVEL)+' $HOME/v8/include/v8-version.h | tr -s ' ' | cut -f 3 -d ' ' | tr '\n' ' ' | awk '{ printf "%s.%s.%s.%s", $1, $2, $3, $4 }'
