#!/usr/bin/env bash

grep -E '^#define\s(MAJOR_VERSION|MINOR_VERSION|BUILD_NUMBER|PATCH_LEVEL)+' $HOME/v8/src/version.cc | tr -s ' ' | cut -f 3 -d ' ' | tr '\n' ' ' | awk '{ printf "%s.%s.%s", $1, $2, $3 }'
